export const PROVIDERS = [
  {
    id: 'anthropic',
    label: 'Anthropic (API)',
    configKey: 'anthropic_api_key',
    placeholder: 'sk-ant-...',
    hint: 'console.anthropic.com → Settings → API keys → Create key',
  },
  {
    id: 'claude',
    label: 'Claude (claude.ai)',
    configKey: 'claude_token',
    placeholder: 'sessionKey:routingHint',
    hint: 'Lancer "claude auth" ou F12 → Cookies → sessionKey + routingHint',
  },
  {
    id: 'gemini',
    label: 'Gemini (Google AI)',
    configKey: 'gemini_api_key',
    placeholder: 'AIza...',
    hint: 'aistudio.google.com → Get API Key',
  },
  {
    id: 'openai',
    label: 'OpenAI (ChatGPT)',
    configKey: 'openai_api_key',
    placeholder: 'sk-...',
    hint: 'platform.openai.com → Settings → API keys → Admin key',
  },
  {
    id: 'ollama',
    label: 'Ollama',
    configKey: 'ollama_session_cookie',
    placeholder: 'session cookie...',
    hint: 'ollama.com → F12 → Application → Cookies → __Secure-session',
  },
  {
    id: 'opencode',
    label: 'OpenCode',
    configKey: 'opencode_session',
    placeholder: 'wrk_01...:st_...',
    hint: 'opencode.ai/console → F12 → Cookies → __Host-console_session (+ workspace ID wrk_... de l’URL)',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    configKey: 'openrouter_api_key',
    placeholder: 'sk-or-v1-...',
    hint: 'openrouter.ai → Keys → Create key',
  },
] as const
